// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AssemblyCSharp
{
	public static class TransformHelper
	{
		public static void SmoothLookAt2D(Transform owner, Transform target, float speed){
			Quaternion rotation = Quaternion.LookRotation(target.position - owner.position);
			Quaternion cache = Quaternion.Slerp(owner.rotation, rotation, speed * Time.deltaTime);
			owner.eulerAngles = new Vector3(0,0,cache.eulerAngles.z);
		}
	}
}

